#!/bin/bash
# vim:foldmethod=marker
###############################
##			     ##
##	COMPii KEYBINDS      ##
##			     ##
###############################

#: SYSTEM {{{

## Media Player Controls ##
{XF86AudioPlay,XF86AudioPause,XF86AudioNext,XF86AudioPrev}
	mpc {toggle,toggle,next,prev}

## Edit Configs ##
super + F12
	dmenu_configedit

## Reolad SXHKD ##
super + Escape
	pkill -USR1 -x sxhkd

## Shutdown Menu ##
super + shift + Escape
	daisy

#: }}}

##		  ##
##  APPLICATIONS  ##
####################

# common applications 
super + {Return,r}
	{st,runprompt}

# edit configs or scripts
super + {_,alt +} F12
	{dmenu_configedit,kitty vim ~/.scripts}

# take a screenshot
Print
	scrot -e mv $f $HOME/Scrots/


##		   ##
##  BSPWM HOTKEYS  ##
#####################

super + {_,shift +} b
	xdo activate -N{firefox || firefox,qutebrowser || qutebrowser}

super + e 
	xdo activate -N ranger || st -c ranger -e ranger
super + shift + e
	xdo activate -N dolphin || dolphin

super + m
	xdo activate -N ncmpcpp || st -c ncmpcpp -e ncmpcpp -s media_library

super + s
	xdo activate -N Steam || steam

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift +} q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
#super + m
#	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,shift + t,space,f}
	bspc node -t {tiled,pseudo_tiled,\~floating,\~fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + {_,shift + }bracket{left,right}
	bspc {desktop -f,node -d} {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} {1-9,0}

# focus or send to the given monitor
super + ctrl {_,alt + }{j,k} 
	bspc {monitor -f,node -m} {DVI-D-0,HDMI-0} --follow

#
# preselect
#

# preselect the direction
#super + ctrl + {h,j,k,l}
#	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
#super + alt + {h,j,k,l}
#	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
#super + alt + shift + {h,j,k,l}
#	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}
